version: "3.12.3"

services:
  django:
    image: django-docker:0.0.1
    container_name: django
    build: .
    ports:
     - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=sigmasigmasigma
      - ALLOWED_HOSTS=localhost,127.0.0.1