# Not in use for linux (local use ONLY)
version: "3.12.3"

services:
  django:
    image: django-docker:0.0.1
    container_name: django
    build: .
    command: python manage.py runserver
    ports:
     - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=development-key-exposedEUkm398278sunL98e89
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CSRF_TRUSTED_ORIGINS=localhost,127.0.0.1